#!/bin/bash

# Napisat skriptu koja ce pronaci sve datoteke koje su promijenjene u zadnjih n minuta 
# (broj n zadan preko argumenta) u "/home/username" direktoriju i ispisati i komprimirati
# u "backup.tgz"

n=$1

adr=$PWD

cd /home/$USER

find /home/$USER -maxdepth 1 -type f -mmin -$n -not -path "*/.*" | rev | cut -d'/' -f 1 | rev | xargs tar cvf backup.tgz

cd $adr

#napomena: napravio sam da hidden fileovi nisu ukljuceni 
