#!/bin/bash

IP=$1									#pretpostavka: pravilan unos adrese
portNum=$2								#pretpostavka: unos indeksa porta

#echo $IP
#echo $portNum

sudo lsof -i -P -n | grep ":$portNum " | grep "$IP" | grep "LISTEN"     #grepanje ispisa lsof->pronalazak zeljenog porta




